### ISSUE TITLE
!theme does not seem to be sending the whisper to the chat user.

### ISSUE THREAD

**Issue by chancesm** [MichaelJolley/vscode-twitch-themer#105]
As seen in chat on Thursday, Aug 22. 
## Expected
Typing !theme in chat should result in a received whisper with the available themes.
## Actual
Typing !theme in chat yields no results. Tested in chat by at least two users. All confirmed no whisper received.

**Comment by MichaelJolley** [comment]
Thanks for recording this for us @chancesm!  

![bitmoji](https://render.bitstrips.com/v2/cpanel/b60cb965-cc0a-4365-8d1f-8d56e9255948-b24761f5-99bf-4885-9465-63838b10c2c3-v1.png?transparent=1&palette=1&width=246)

@all-contributors please add @chancesm for bugs

**Comment by cmjchrisjones** [comment]
I don't think this is an issue any longer (I just tested it @MichaelJolley) so perhaps its been fixed but this issue remained open, can this be closed?
