### ISSUE TITLE
Themer not connecting while streaming

### ISSUE THREAD

**Issue by PatPat1567** [MichaelJolley/vscode-twitch-themer#119]
In VS code, version 1.43.0, I am unable to connect to twitch themer while streaming using the extension button in the status bar. I get no errors in the output window or errors in notification toasts.

https://www.twitch.tv/patpat1567/clip/ObedientMiniatureWatercressOptimizePrime

Here is my latest version information from VS Code. 
![image](https://user-images.githubusercontent.com/41209202/76723532-97faed80-6715-11ea-9454-7d848b167f7a.png)

**Comment by MichaelJolley** [comment]
@PatPat1567 Did you sign in first? or just install and press Connect?
