### ISSUE TITLE
Problem when using !install command

### ISSUE THREAD

**Issue by MichaelJolley** [MichaelJolley/vscode-twitch-themer#120]
Occasionally, when using the `!theme install` command, the extension doesn't prompt for the install.

An example would be [saikumarchinna.rainbow](https://marketplace.visualstudio.com/items?itemName=Saikumarchinna.rainbow).

I confirmed that this extension:
- has a public repository
- has a package.json in the root of the repository
- the package.json includes themes for the extension

**Comment by parithon** [comment]
Another example has been brought up: feihuangtengda.vscode-turtle

**Comment by MichaelJolley** [comment]
Holy moly. Did I actually create an issue for this?  @parithon aren't you proud? 😄

**Comment by parithon** [comment]
@MichaelJolley It actually looks like the themer worked as expected: `feihuangtengda.vscode-turtle` does not register as a theme in the `contributes` section of the package.json file.

As for the `saikumarchinna.rainbow` theme. The package.json is formatted improperly which fails to allow us to convert it into JSON. This prevents us from verifying the extension is configured to contribute themes.

**Comment by MichaelJolley** [comment]
Confirming this seems to be working correctly.  Closing.
