### ISSUE TITLE
Some themes aren't triggering the notification when !theme install is invoked in chat!

### ISSUE THREAD

**Issue by cmjchrisjones** [MichaelJolley/vscode-twitch-themer#131]
A couple of recent examples of this are

- robertrossmann.remedy
- cmjchrisjones1.bbbthemes
- ms-vscode.PowerShell

@parithon - as requested :)

**Comment by parithon** [comment]
Could not reproduce on my test machine. We will need to investigate more once @MichaelJolley pulls in PR #132
