### ISSUE TITLE
Add tests to project

### ISSUE THREAD

**Issue by MichaelJolley** [MichaelJolley/vscode-twitch-themer#3]
As this project grows we definitely want to test changes before a release.

**Comment by sorskoot** [comment]
I could use some practice on writing tests in TypeScript. I'll add them.

**Comment by MichaelJolley** [comment]
Great @sorskoot!  Be sure to checkout @parithon's work on testing.  I think he's got a foundation for us to build on.

**Comment by MichaelJolley** [comment]
@all-contributors please add @MichaelJolley for tests
