### ISSUE TITLE
Bug: chatClientUserName default to themichaeljolley

### ISSUE THREAD

**Issue by PatPat1567** [MichaelJolley/vscode-twitch-themer#34]
The constant chatClientUserName is set to themichaeljolley, which causes several commands (chat disconnect, ban, unban, follower only, follower only off) from being able to be used if another streamer is using themer extension.

**Comment by PatPat1567** [comment]
This may be resolved with pull request #32

**Comment by MichaelJolley** [comment]
It was indeed.  Gracias @parithon
