### ISSUE TITLE
Exclude shame themes from the random command

### ISSUE THREAD

**Issue by mholloway24** [MichaelJolley/vscode-twitch-themer#37]
To prevent unsuspecting users from being shamed on a random theme command, shamed themes shouldn't be included in the random theme command
OR... Let the broadcaster determine if shamed themes should be included within the random command

**Comment by MichaelJolley** [comment]
@mholloway24 This is a really good idea! No need to needlessly shame. 😄 

Thinking about how to handle this made me realize that while shame themes are included in the list of random, the actual "shame" sound clip and message in chat only occurs if you specifically say "!theme HotDogStand".

It's actually not something that fires as a result of the extension, but as part of our [io](https://github.com/MichaelJolley/io) Twitch bot.

So no change needed for the extension code.  Thanks for helping us think it through!

**Comment by MichaelJolley** [comment]
@all-contributors please add @mholloway24 for ideas
