### ISSUE TITLE
Bug: Punctuation causes theme to not change

### ISSUE THREAD

**Issue by mholloway24** [MichaelJolley/vscode-twitch-themer#40]
When punctuation is included in the !theme <theme name> command, it causes the extension to not fire. This issue will remove all punctuation to match the theme names.

**Comment by PatPat1567** [comment]
Can you provide an example?

**Comment by MichaelJolley** [comment]
An example would be if someone were to type:

```
!theme Lasers,
```

We'd want to remove the comma.  I think this really only applies to commas since our whisper comma delimits the theme names.
