### ISSUE TITLE
Let the user know if their !theme {themeName} failed.

### ISSUE THREAD

**Issue by John-Kryspin** [MichaelJolley/vscode-twitch-themer#51]
The user should get a whisper if their theme command failed to switch the theme. This will help people who submit a request but spell something wrong and their theme doesn't go through.

**Comment by MichaelJolley** [comment]
Nice idea @John-Kryspin!  Let's discuss it on stream.  

I'm going to leave this link here so I can reference it then.  
https://dev.twitch.tv/docs/irc/guide/#command--message-limits

Specifically want to talk about our whisper rate limits.  We're sending whispers for `!theme list` but even that may hit the limit.  The whisper limits are not exactly clearly stated.

In the meantime, let's get all-contributors involved to show love for the ideas.

@all-contributors please add @John-Kryspin for ideas

**Comment by MichaelJolley** [comment]
Let's do this but rather than a whisper let's write the message in chat.  Maybe something like:

```
{twitchUsername}, {theme} is not a valid theme name or isn't installed.  You can use !theme list to get a list of available themes.
```

**Comment by John-Kryspin** [comment]
Awesome, Let me change the PR to support this idea.
