### ISSUE TITLE
Need better (any) documentation on how to get the environment working locally.

### ISSUE THREAD

**Issue by MichaelJolley** [MichaelJolley/vscode-twitch-themer#54]
A discussion in [Discord](https://discord.gg/XSG7HJm) was related to the need for better documentation for getting the environment working locally.

I'm adding this as an issue rather than doing it to allow others a chance to contribute something other than code. 

After some period of time, if not completed, I'll pick it back up and push it through.

Thanks @John-Kryspin for the feedback.

**Comment by PatPat1567** [comment]
I'll add some documentation.

**Comment by MichaelJolley** [comment]
@PatPat1567 do you think we need documentation for this still?  I think it's just a matter of pulling the code and running npm tasks right?

**Comment by PatPat1567** [comment]
That's correct. We probably don't need the documents anymore.
