### ISSUE TITLE
Modify the follower & sub only state values to be settings

### ISSUE THREAD

**Issue by MichaelJolley** [MichaelJolley/vscode-twitch-themer#55]
Allow those properties to be set in VS Code rather than chat only.

**Comment by John-Kryspin** [comment]
I'm trying to get this going! Can I claim it?

**Comment by MichaelJolley** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/08e1c0f6-70b3-4c70-aa7a-efb6fd9a2da8-b24761f5-99bf-4885-9465-63838b10c2c3-v1.png?transparent=1&palette=1&width=246)
