### ISSUE TITLE
Update available theme cache command

### ISSUE THREAD

**Issue by parithon** [MichaelJolley/vscode-twitch-themer#6]
Once the bot is loaded we would need to restart the bot to load any new themes downloaded. We should create a command to update the themes while the bot is running.

**Comment by MichaelJolley** [comment]
Added a !theme refresh to update the list and also reset the timers for people requesting available themes.  Both of those actions only occur if the requester is the broadcaster.

**Comment by MichaelJolley** [comment]
@all-contributors please add @parithon for ideas
