### ISSUE TITLE
themer reconnects each time a new instance of code is opened

### ISSUE THREAD

**Issue by PatPat1567** [MichaelJolley/vscode-twitch-themer#72]
When themer is installed, themer will auto reconnect, even if previously disconnected, when a new instance of code is opened. 

Twitch clip for reference:
https://clips.twitch.tv/DifficultFreezingSlothAliens

**Comment by MichaelJolley** [comment]
@PatPat1567 I think this is somewhat a duplicate of the other issue.  Going to copy this Twitch clip there and close this one out.
