### ISSUE TITLE
themer connects by default

### ISSUE THREAD

**Issue by PatPat1567** [MichaelJolley/vscode-twitch-themer#73]
Need to update themer to require the streamer to connect to chat manually, rather than automatically connect when signed in.

**Comment by John-Kryspin** [comment]
Maybe we should make it a setting?

Connect Automatically - []

**Comment by MichaelJolley** [comment]
Twitch clip for reference:
https://clips.twitch.tv/DifficultFreezingSlothAliens

**Comment by MichaelJolley** [comment]
This is great feedback from @clarkio.

I lean toward no setting.  Just don't automatically connect when the extension starts.  So connecting/disconnecting to chat is a manual process through the command pallette.  Thoughts?

@all-contributors please add @clarkio for user testing.

@all-contributors please add @PatPat1567 for bugs.

@all-contributors please add @John-Kryspin for ideas.

**Comment by MichaelJolley** [comment]
@all-contributors please add @PatPat1567 for bugs.

**Comment by MichaelJolley** [comment]
@all-contributors please add @John-Kryspin for ideas.

**Comment by MichaelJolley** [comment]
@all-contributors please add @clarkio for user testing.

**Comment by MichaelJolley** [comment]
Working on this one now

**Comment by clarkio** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/31eaf530-5a85-43e9-bc48-098e06ab8c90-1af5294e-37d3-4206-9bf6-d21903386d2f-v1.png?transparent=1&palette=1&width=246)

**Comment by MichaelJolley** [comment]
The new refactoring prevents the extension from connecting to chat automatically. Also allows clicking the status bar icon to toggle connecting/disconnecting from chat.  

On disconnect, the VS Code theme will revert to whatever theme the streamer had originally when they launched VS Code.  (So you can go back to Night Owl post-stream just by disconnecting from chat @clarkio) 😄
