### ISSUE TITLE
Publicly shame people who try to set the theme to HotDogStand

### ISSUE THREAD

**Issue by NotMyself** [MichaelJolley/vscode-twitch-themer#8]
https://www.youtube.com/watch?v=SrDSqODtEFM

**Comment by MichaelJolley** [comment]
Let's add a setting to allow choosing multiple "shame" themes and send a message to chat shaming the requester.

**Comment by MichaelJolley** [comment]
So this is now handled. 

"But Mike, I don't see any commits are PR's related to it..."

Yes, I know.  Trust me.  It's handled.  😆
