### ISSUE TITLE
Test follower only mode in Themer class

### ISSUE THREAD

**Issue by MichaelJolley** [MichaelJolley/vscode-twitch-themer#84]
When we refactored the follower only setting to be a VS Code setting rather than an extension setting, the tests for follower only were not updated.  Need to add the following tests:

- When the extensions AccessState setting is set to `Followers`, only followers of the channel should be allowed to change the theme.

**Comment by calebmckay** [comment]
I'd be interested in working on this and #85 to get my feet wet in TypeScript.

**Comment by MichaelJolley** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/f04860f3-6cb3-414f-b640-455c31a4df1c-b24761f5-99bf-4885-9465-63838b10c2c3-v1.png?transparent=1&palette=1&width=246)

We've had several people contribute to learn TypeScript.  You'll crush it!  Be sure to check out our [CONTRIBUTING.md](https://github.com/MichaelJolley/vscode-twitch-themer/blob/master/CONTRIBUTING.md) for PR instructions/help.  Good luck!
