### ISSUE TITLE
Error when i run the command to sign in

### ISSUE THREAD

**Issue by TheCynicalLiger** [MichaelJolley/vscode-twitch-themer#88]
The name org.freedesktop.secrets was not provided by any .service files

**Comment by HeCodes2Much** [comment]
oh ```pacman -S gnome-keyring``` seems to have fixed this issue

**Comment by MichaelJolley** [comment]
Hi @HeCodes2Much, you're running on Linux?

**Comment by HeCodes2Much** [comment]
yes im running it on arch linux and yes it works right after i added gnome-keyring

**Comment by MichaelJolley** [comment]
Thanks for letting us know.  We'll update the README.md to include a note if you're running on Arch Linux.

@all-contributors please add @HeCodes2Much for userTesting
