### ISSUE TITLE
Theme Installer

### ISSUE THREAD

**Issue by Flyken271** [MichaelJolley/vscode-twitch-themer#93]
Install a theme that isn't already installed when someone requests a theme and automatically apply.

(using the official marketplace so it doesn't open up any sort of backdoor)

**Comment by MichaelJolley** [comment]
@allcontributors please add @Flyken271 for ideas

**Comment by MichaelJolley** [comment]
I like this idea a lot, but I'm questioning its feasibility after reviewing some requirements.  Let's discuss. 
 How could we do this?

My first thought is the whispered list of themes is not actually the extension name.  This causes the following issues we'll need to solve before implementing:

1. **How do we determine the theme name in the extension?** Many theme extensions contain multiple themes.  So in the example where a theme is named "Great Theme," it may contain multiple themes named "Great Theme (light)" and "Great Theme (dark)".
2. **How do we determine the extension name?** This is somewhat related to 1 but relates to the actual extension name.  Using 1's example, let's say we somehow determine "Great Theme" is the actual extension name.  The id of the extension (which we'd need to install it) is likely different.  For instance, the actual extension name of our "Twitch Themer" extension is `MichaelJolley.vscode-twitch-themer`.  How do we determine the extension id for the theme we want to pull down?

**Comment by MichaelJolley** [comment]
@parithon do you have any thoughts on this?

**Comment by parithon** [comment]
To know what the theme name is we should be able to examine the extension's manifest:

```JSON package.json
"contributes": {
   "themes: [
      {
         "label": "My Name",
         "uiTheme": "vs-dark",
         "path": "./my-theme.json"
      }
   ]
}
```

As for the installation of a theme from the marketplace, I'm sure it is possible... but we would first need to determine how we can query the marketplace for the theme name (or extension name) and then how to install it. 

To install the theme, I believe we may be able to learn from the 'Settings Sync' extension as a guide for how to install the theme. But we still need to learn how to find the theme in the marketplace.

**Comment by parithon** [comment]
Looking further into the idea of searching the marketplace for the theme, it appears that multiple people can upload a project with the same name. For example, there are at least 3 published [Base16 Themes](https://marketplace.visualstudio.com/search?term=Base16%20Themes&target=VSCode&category=Themes&sortBy=Relevance) themes. Therefore, how do we know which the user actually wanted?
