### ISSUE TITLE
Assign numbers to themes.

### ISSUE THREAD

**Issue by surlydev** [MichaelJolley/vscode-twitch-themer#95]
I propose a PR whereby the stream participants can select a theme by number.

Typing some of the theme names can be troublesome and error-prone, for example "Monokai Pro (Filter Machine)"

I propose each theme having a number assigned, so that they can be selected by a numeral, for example !theme 1 would be "Hotdog Stand". ;)

**Comment by MichaelJolley** [comment]
@surlydev, thanks for the suggestion.  I think this one may be a little confusing for users and hard to maintain over time.  Going to close, but gracias for the ideas.

![bitmoji](https://render.bitstrips.com/v2/cpanel/e19d1515-b426-4107-aad4-d62c37a20430-b24761f5-99bf-4885-9465-63838b10c2c3-v1.png?transparent=1&palette=1&width=246)

@all-contributors please add @surlydev for ideas
