### ISSUE TITLE
Add !theme random [Dark|Light] 

### ISSUE THREAD

**Issue by mholloway24** [MichaelJolley/vscode-twitch-themer#98]
When doing a random theme, add the ability to specify random within a subset (light/dark) of the theme list.

**Comment by mholloway24** [comment]
Per @parithon, we can investigate the manifest for each theme to determine which subset the theme should be included in

**Comment by MichaelJolley** [comment]
Great idea @mholloway24!  I can't believe I had talked myself out of it.  Thankfully @parithon came to the rescue.  We ended up adding this on stream today and it's out the door already.

![bitmoji](https://render.bitstrips.com/v2/cpanel/27b14f57-f25e-4eb2-a4e5-b75e089c772a-b24761f5-99bf-4885-9465-63838b10c2c3-v1.png?transparent=1&palette=1&width=246)
